// DO NOT EDIT -- generated by ./configure

#include "config.h"

const char *yadex_etc_path[] =
{
  ".",
  "~/.yadex/%v",
  "~/.yadex",
  "/etc/yadex/%v",
  "/etc/yadex",
  0
};

const char *yadex_share_path[] =
{
  ".",
  "~/.yadex/%v",
  "~/.yadex",
  "/usr/local/share/games/yadex/%v",
  "/usr/local/share/games/yadex",
  0
};

